name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.5

      - name: Tidy dependencies
        run: go mod tidy

      - name: Verify Dependencies
        run: go mod verify

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run Tests
        run: go test -race ./...